name: Toybox CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check secrets
      run: |
        _e() {
            echo "$1 secret is not set"
            ((count++))
        }
        count=0
        if [ -z "${{ secrets.TG_BOT_TOKEN }}" ]; then
            _e "TG_BOT_TOKEN"
        fi
        if [ -z "${{ secrets.TG_CHAT_ID }}" ]; then
            _e "TG_CHAT_ID"
        fi
        # exit if count greater than 0
        if [ "$count" -gt 0 ]; then
            exit $count
        fi

    - name: NDK Setup
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        LATEST_VER=$(gh api "repos/android/ndk/tags" --jq '.[0].name')
        wget -q https://dl.google.com/android/repository/android-ndk-${LATEST_VER}-linux.zip
        unzip -q android-ndk*.zip
        rm android-ndk*.zip
        mv android-ndk* android-ndk
        echo "ANDROID_NDK_PATH=$PWD/android-ndk" >>$GITHUB_ENV

    - name: Build toybox
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        chmod a+x *.sh
        ./build_toybox.sh
